baseURL = "https://example.com"
languageCode = "en-us"
title = "Inspired / (G.K)"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Gibran Kichlu"

[params]
author = "Gibran Kichlu"
description = "Inspired is my storehouse of ideas, thoughts and possibilities."
dateFormat = "2022-01-02"
paginationSinglePost = true
style = "light-without-switcher"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "linkedin"
url = "https://www.linkedin.com/in/gibran-k-660a8b57/"

[[params.social]]
id = "github"
url = "https://github.com/gkscloud"

[[params.header]]
id = "tags"
name = "Browse Tags"
url = "/tags/"
weight = 1

[[params.header]]
id = "archive"
name = "Archive"
url = "/posts/"
weight = 2

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
name = "Experience"
identifier = "projects"
url = "/post/projects/"
weight = 2


[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
